version: 2
jobs:
  validate_integrations:
    docker:
      - image: circleci/node:10.14-browsers

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - run: node scripts/validate.js

  testcafe:
    docker:
      - image: circleci/node:10.14-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

workflows:
  version: 2
  # tests-every-5min:
  #   triggers:
  #     - schedule:
  #         # cron: "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *"
  #         # every minute: * * * * *
  #         cron: 0,5,10,15,20,25,30,35,40,45,50,55
  #         # 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - testcafe:
  #         context: frontend-deploy
  #         filters:
  #           branches:
  #             only:
  #               - master
  build-test-and-deploy:
    jobs:
      - validate_integrations:
          context: frontend-deploy
      - deploy:
          context: frontend-deploy
          filters:
            branches:
              only:
                - master